services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
     - POSTGRES_USER: postgres
     - POSTGRES_PASSWORD: secret
     - POSTGRES_DB: campaign
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_dir:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_dir:
    driver: local

networks:
  app-network:
    driver: bridge